# Generated by Django 4.0.1 on 2022-01-28 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceCenter', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name="User's first name")),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name="User's last name")),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="User's email")),
                ('home_center', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.servicecenter', verbose_name='What location does this user work at?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='The User object associated with this profile')),
            ],
        ),
    ]
