# Generated by Django 4.0.1 on 2022-01-28 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the service center')),
                ('state', models.CharField(max_length=50, verbose_name='State of this service center')),
                ('street_address', models.CharField(max_length=50, verbose_name='Address of the service center')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code of this service center')),
                ('manager', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Which manager runs this center?')),
            ],
        ),
    ]
