# Generated by Django 4.0.1 on 2022-01-28 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServiceCenter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicecenter',
            name='manager',
        ),
    ]
