# Generated by Django 4.0.1 on 2022-01-28 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('ServiceCenter', '0002_remove_servicecenter_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecenter',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Profiles.profile', verbose_name='Which manager runs this store?'),
        ),
    ]
