# Generated by Django 4.0.1 on 2022-01-28 16:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ServiceCenter', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryEquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Vent', 'Ventilator'), ('CPAP', 'CPAP Device'), ('O2', 'Oxygen Device'), ('Other', 'Other Equipment')], max_length=8, verbose_name='Type of Equipment')),
                ('manufacturer', models.CharField(max_length=50, verbose_name='What manufacturer makes this equipment?')),
                ('model_number', models.CharField(max_length=50, verbose_name='Model Number for this equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, verbose_name='Unique ID of this transaction')),
                ('customer_id', models.CharField(default='', max_length=50, null=True, verbose_name='ID of the customer using this equipment')),
                ('location_status', models.CharField(choices=[('SC', 'At Service Center'), ('CU', 'With the customer'), ('RC', 'Sent to Repair Center'), ('RT', 'Retired Unit')], max_length=5, verbose_name='The current location of this equipment')),
                ('equipment_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Retired')], max_length=1, verbose_name='Is this equipment actively billing?')),
                ('software_version', models.CharField(default='', max_length=20, null=True, verbose_name='The current version of software on this equipment')),
                ('serial_number', models.CharField(max_length=50, null=True, verbose_name='The Serial Number Of this Device')),
                ('notes', models.TextField(null=True, verbose_name='Notes from this service visit')),
                ('service_check_date', models.DateTimeField(verbose_name='When Transaction was the check done?')),
                ('transaction_date', models.DateTimeField(verbose_name='When Transaction was submitted')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.servicecenter', verbose_name='Which service center is servicing this equipment?')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, verbose_name='The Serial Number Of this Device')),
                ('customer_id', models.CharField(default='', max_length=50, null=True, verbose_name='ID of the customer using this equipment')),
                ('location_status', models.CharField(choices=[('SC', 'At Service Center'), ('CU', 'With the customer'), ('RC', 'Sent to Repair Center'), ('RT', 'Retired Unit')], default='SC', max_length=5, verbose_name='The current location of this equipment')),
                ('equipment_status', models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('R', 'Retired')], default='A', max_length=1, verbose_name='Is this equipment actively billing?')),
                ('software_version', models.CharField(default='', max_length=20, null=True, verbose_name='The current version of software on this equipment')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InventoryItems.inventoryequipmenttype', verbose_name='Which Type of Equipment is this?')),
                ('service_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServiceCenter.servicecenter', verbose_name='Which service center is servicing this equipment?')),
            ],
        ),
    ]
