# Generated by Django 4.0.1 on 2022-01-28 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InventoryItems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='Who was this transaction submitted to?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='submitter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submitter', to=settings.AUTH_USER_MODEL, verbose_name='Who submitted this transaction?'),
            preserve_default=False,
        ),
    ]
