# Generated by Django 4.0.1 on 2022-01-31 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('InventoryItems', '0002_transaction_approver_transaction_submitter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profiles.profile', verbose_name='The individual who approves the transaction'),
        ),
    ]
