# Generated by Django 4.0.1 on 2022-02-02 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InventoryItems', '0004_alter_transaction_service_check_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Was this transaction approved by a manager?'),
        ),
    ]
